ircbot/weather.py

The black text previously gets hidden when on a dark background, so reset to whatever the default text color is instead.
I'm conflicted on whether this is actually more readable than it was before since `bisect` is more complicated than just a bunch of `if`/`else` blocks. I do think it's reasonably clear though once the documentation about it has been read. Thoughts?

Use bisect for weather temperature ranges and reset text color properly

---

ircbot/ircbot.py
ircbot/plugin/create.py

This is for [rt#6971](https://rt.ocf.berkeley.edu/Ticket/Display.html?id=6971). It logs lines like `jvperrin created (Jason Perrin, Calnet UID: 1101587)` in #atool. I also moved all the logging stuff to the `create` plugin, since there was a comment about doing that.

Log calnet UID and callink OID, move logging to plugin

---

ircbot/plugin/github.py

```
<asottile> https://github.com/pre-commit/pre-commit#foo
<create> pre-commit/pre-commit#foo | 1743 stars | A framework for managing and maintaining multi-language pre-commit hooks.
<create-asottile> pre-commit/pre-commit | 1743 stars | A framework for managing and maintaining multi-language pre-commit hooks.
```

Allow fragments in github urls

---

ircbot/plugin/regex.py

This reverts commit fc5e2da06f972ace7fb2ff2335aac06cd106314e.
@jvperrin @chriskuehl this seems to fix this for me.  I'm really not sure why though

Revert "Make trailing delimiter on replacements optional"

---

ircbot/plugin/quotes.py

Before:
```
<ckuehl> !quote rand bsd
<create> ckuehl: There are... no quotes?
```
After:
```
<ckuehl> !quote rand bsd
<create-ckuehl> Quote #60: <asottile> ckuehl: it just hit me, the irony of always shitting on BSD, but like berkeley <asottile> myabe I've had too many drinks
```

Make "!quote rand" not case-sensitive

---

ircbot/plugin/request_tracker.py

Security tickets can be sensitive, so we probably shouldn't broadcast some of their sensitive information (like the subject line) to the world.

Hide rt ticket names for security queue

---

ircbot/plugin/regex.py

Do not try to substitute on messages which themselves are (or contain) substitution commands. This way, users can retry substitutions on recent messages without later substitution commands matching on earlier substitution commands instead of the intended message.
Before:
```
<you> This sentance has a mistake in it
<you> s/sentance/sentendce
<create> <you> This sentendce has a mistake in it
<you> s/sentance/sentence
<create> <you> s/sentence/sentendce
<you> !sux create
```
After:
```
<you> This sentance has a mistake in it
<you> s/sentance/sentendce
<create> <you> This sentendce has a mistake in it
<you> s/sentance/sentence
<create> <you> This sentence has a mistake in it
<you> create: thanks
```

regex: better allow retry of substitutions

---

requirements.txt

https://nvd.nist.gov/vuln/detail/CVE-2018-10903
Version 2.3 is unaffected by the CVE.

update cryptography requirement

---

ircbot/ircbot.py
ircbot/plugin/discourse.py

This works exactly like the RT shortcut plugin:
```
14:13 <@dkessler> d#129
14:13 <create-dkessler> dkessler: d#129: "Kubernetes" | Projects, started by dkessler | https://ocf.io/d/129
```

Add Discourse shortcut plugin

---

ircbot/plugin/macros.py

this brings a simple adaptation of phabricator macros\[0\] to OCF. they are a staple at facebook
now you can do something like
to add do `#m add <slug> <link>` and delete `#m delete <slug>`
\[0\]: https://secure.phabricator.com/project/profile/283/

Phabulous Macros @ OCF

---

ircbot/plugin/lab.py

"who is in the lab" output currently inserts U+200B ZERO WIDTH SPACE
into usernames to prevent clients from alerting the mentioned users.
While this usually works as intended, section 23.2 of the Unicode
standard [1] indicates that U+200B "indicates a word break or line break
opportunity", permitting clients to wrap lines in the middle of
usernames.  To prevent this, Use U+2060 WORD JOINER, a zero-width
no-break space, instead.
[1] http://www.unicode.org/versions/Unicode11.0.0/ch23.pdf

who is in the lab: prevent line breaks in middle of usernames

---

ircbot/ircbot.py
ircbot/plugin/twitter.py

Requires adding a new section to the config like so:
```
[twitter]
apikey=<"API key" from developer.twitter.com>
apisecret=<"API secret key" from developer.twitter.com>
```
I used a personal key to test but we should apply for an API key as an organization.
Closes #60.

add a plugin to show the contents of a linked tweet

---

ircbot/plugin/templates/help.html

The `<tt>` tag is considered obsolete (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt). It can be replaced with CSS, so this commit will fix it.

Replace tt tag with class="command"

---

ircbot/ircbot.py
ircbot/plugin/templates/help.html
ircbot/plugin/wide.py

This adds optional help text to listeners, removes message logging for commands, and adds help text for wide commands and does a bit more simplification to make thiccen a partial too.
This also makes thicc messages have more space between words, which makes the messages easier to actually read. (for example, `丅卄工丂 丅乇丂丅 从乇丂丂卂厶乇` becomes `丅卄工丂　丅乇丂丅　从乇丂丂卂厶乇`)

Some small improvements to help text, message logging, and wide commands

---

ircbot/plugin/turing.py

turing: account for -slack nicks when adding 0-length spaces

---

ircbot/ircbot.py
ircbot/plugin/kanboard.py

This should work. The only problem is that querying the KanboardTask is 401'ing. My suspicion is that the apikey in /etc/ocf-ircbot/ocf-ircbot.conf isn't right but I can't really check that since I'm not an admin on Kanboard.

display more info about Kanboard tasks (#106)

---

ircbot/plugin/github.py

If someone types an invalid GitHub repository name, it triggers an exception and emails rootspam. This PR fixes that behavior by silently ignoring the error.

github: catch and ignore NotFoundErrors

---

ircbot/plugin/shorturls.py

If someome tries to add a shorturl that already exists, it currently throws an IntegrityError. This commit changes it to not throw an exception, and instead give a helpful reminder that the user probably wants to use the `replace` subcommand.

shorturl: catch MySQL integrity error when adding

---

ircbot/plugin/lab.py

To facilitate easier typing experience on mobile, with this PR, one can doubly type a character while summoning create with command for `who is in the lab` and create will understand it.

make `wiitl` work like summoning piiinnngg

---

Makefile
ircbot/plugin/turing.py

think about how much time we'll save
also, offset the default port selection by 10 to allow concurrently running ocfweb at default settings

alias turing to !t

---

ircbot/plugin/weather.py

Fixes a couple of issues with display in the weather plugin.

Weather plugin fixes

---

ircbot/plugin/shorturls.py

To address: #151
When a `ValueError` is raised, send the error message back to the user.
Test usage:
```
<zachary> !shorturl add ^badurl ~zachary
<create-zachary> zachary: shorturl '^badurl' contains illegal characters
```

Handle invalid characters in shorturls/add

---

ircbot/plugin/macros.py
ircbot/plugin/shorturls.py

* Updated shorturls and macros to use alias
* Alias could be edited to use a proxy function that can appear differently on ircbot.ocf.berkeley.edu

Add `update` keyword as alias for `replace`

---

ircbot/ircbot.py
ircbot/plugin/notify.py

This adds a mechanic for adding "notification groups" that you can use to quickly ping a subgroup of people (sort of like Slack teams, which are a paid feature). Include something like `!!gm` or `!!finance-comm` to expand to ping each individual member in those notification groups.
Notification groups are comprised of owners and members. Both are pinged during normal expansion. Additionally, owners have permissions to add other users or owners.
Anyone can join any group by using `addme` and leave by using `removeme` (as a member, not an owner).
Finally groups can be nested by adding `!!groupname` to another group. This also allows you to create aliases, by creating a group where the only member is the canonical group.

Add notify plugin
