ocf/ircbot

ircbot/emoji.py, ircbot/ircbot.py
```
(2:50:12 PM) asottile: create-asottile: remoji 🤔
(2:50:12 PM) create-asottile: asottile: 🤔: THINKING FACE
```
=> Add remoji command

ircbot/emoji.py, ircbot/ircbot.py
sorry about the ram
```
(3:47:35 PM) asottile: create-asottile: emoji cat
(3:47:35 PM) create-asottile: asottile: Showing 1-50 of 82 results
(3:47:35 PM) create-asottile: asottile: ªº×ʕ໋࡙༁၌⊍⌖⑆✆✕✖⨰⨱⨴⨵⨶⨷⨻⫁⫂⯐〾ꊶꧦꩰ챁𐇬𐩿𝅼𝅾𝅿𝆀𝆁𝆭𝩿𝪀𝪁𝪂𝪃𝪄𝪅𝪆🇦🇧🇨🇩🇪
(3:47:43 PM) asottile: lol
(3:47:58 PM) asottile: create-asottile: emoji thinking
(3:47:58 PM) create-asottile: asottile: 🤔
(3:48:05 PM) asottile: create-asottile: remoji 🤔
(3:48:05 PM) create-asottile: asottile: 🤔: THINKING FACE
(3:48:12 PM) asottile: create-asottile: emoji penguin
(3:48:12 PM) create-asottile: asottile: 🐧
(3:48:17 PM) asottile: create-asottile: remoji 🐧
(3:48:17 PM) create-asottile: asottile: 🐧: PENGUIN
(3:50:19 PM) asottile: create-asottile: emoji aoisjdfkljasdf
(3:50:20 PM) create-asottile: asottile: No results 😢
```
=> Implement 'create emoji ...'

ircbot/emoji.py
```
(4:21:17 PM) asottile: create-asottile: emoji ' a '
(4:21:17 PM) create-asottile: asottile: Showing 1-50 of 448 results
(4:21:17 PM) create-asottile: asottile: ÀÁÂÃÄÅàáâãäåĀāĂăĄąǍǎǞǟǠǡǺǻȀȁȂȃȦȧȺӐӑӒӓӔӕᶏᷓᷲḀḁẚẠạẢảẤ
(4:21:23 PM) asottile: create-asottile: emoji ' cat '
(4:21:23 PM) create-asottile: asottile: 😸😺😻😽😾😿🙀
```
=> Allow quoted arguments to emoji

ircbot/db.py, ircbot/ircbot.py, ircbot/quotes.py, requirements-minimal.txt
Still need to backfill the old ones into the DB, but the code works.
=> Add quotes

ircbot/ircbot.py
I've been waiting to make another appearance in this repo
=> Valuable contribution

ircbot/inspire.py, ircbot/ircbot.py
let create inspire you with a fine selection of quotations from such luminaries as DJ Khaled, NPCs from "Sid Meier's Alpha Centauri," the top three Google search results for "inspirational quotes.", and [inspirobot.me](https://inspirobot.me)
in addition, create can now help answer the eternal question: is jvperrin in the lab?
=> get inspired

ircbot/plugin/ping.py
or poooonng to piiiinng ... or you have a 1/100 chance of annoying create.
=> create responds pong to ping

ircbot/plugin/emoji.py
```
(12:01:41 PM) asottile1: create-asottile remoji  🦅ಠ_ಠ
(12:01:58 PM) create-asottile: asottile1:  : SPACE
(12:01:59 PM) create-asottile: asottile1: 🦅: <<unknown character>>
(12:01:59 PM) create-asottile: asottile1: ಠ: KANNADA LETTER TTHA
(12:01:59 PM) create-asottile: asottile1: _: LOW LINE
(12:01:59 PM) create-asottile: asottile1: ಠ: KANNADA LETTER TTHA
```
=> Don't crash on unknown emoji

ircbot/plugin/channels.py, ircbot/plugin/create.py, ircbot/plugin/help.py, ircbot/plugin/ping.py, ircbot/plugin/templates/help.html, requirements-minimal.txt
Fixes #1
Running at http://supernova.ocf.berkeley.edu:8888/ (will leave this up for a while)
The page is pretty rough right now, but I'm all about shipping something which is at least minimally useful and improving it later :)
The plan is to have the ircbot itself serve this page (the code in this branch does that) and add configs to marathon/lb nginx to route ircbot.o.b.e there.
=> Add a help page

ircbot/plugin/shipit.py
could be too spammy but i find it amusing
=> create wants you to ship your code

ircbot/plugin/shipit.py
```
<ckuehl> shipit
<create-ckuehl> .  o ..
<create-ckuehl>     o . o ooo 
<create-ckuehl>         ...oo 
<create-ckuehl>           __[]__
<create-ckuehl>        __|_o_o_o\__
<create-ckuehl>        \""""""""""/
<create-ckuehl>         \. ..  . / 
<create-ckuehl>    ^^^^^^^^^^^^^^^^^^^^
<ckuehl> shiiipit
<create-ckuehl> .  o ..
<create-ckuehl>     o . o ooo oo oo 
<create-ckuehl>         ...oo oo oo 
<create-ckuehl>           __[]_[]_[]__
<create-ckuehl>        __|_o_oo_oo_o_o\__
<create-ckuehl>        \""""""""""""""""/
<create-ckuehl>         \. .. .. ..  . / 
<create-ckuehl>    ^^^^^^^^^^^^^^^^^^^^^^^^^^
<ckuehl> shiiiiiiiiipit
<create-ckuehl> .  o ..
<create-ckuehl>     o . o ooo oo oo oo oo oo oo oo oo 
<create-ckuehl>         ...oo oo oo oo oo oo oo oo oo 
<create-ckuehl> …
```
=> Make shipit more flexible

ircbot/plugin/github.py
https://github.com/sigmavirus24/github3.py/commit/0244423a5e6a8
=> Fix api break in github3

ircbot/plugin/stack_exchange.py
```
<ckuehl> https://worldbuilding.stackexchange.com/a/114038
<create-ckuehl> Worldbuilding: How can Santa keep his lists when GDPR is around? | 365 votes, 19 answers | June 4, 2018
<ckuehl> https://math.stackexchange.com/questions/2811951/why-is-it-important-for-a-matrix-to-be-square
<create-ckuehl> Mathematics: Why is it important for a matrix to be square? | 43 votes, 6 answers | June 7, 2018
```
=> Print information about Stack Exchange questions/answers

ircbot/ircbot.py, ircbot/plugin/regex.py
=> Don't regex replace across channels

ircbot/plugin/help.py, ircbot/plugin/macros.py, ircbot/plugin/templates/macros.html
=> add help page listing available macros

ircbot/plugin/macros.py, ircbot/plugin/templates/macros.html
address @chriskuehl's comments on #57
=> macros help fixes

ircbot/plugin/create.py, ircbot/plugin/gambling.py
These should be useful as part of the OCF Decision Making Process.
```
<ckuehl> !8ball should we kill printing
<create-ckuehl> ckuehl: very doubtful
```
```
<ckuehl> create-ckuehl: roll 3d6
<create-ckuehl> ckuehl: i rolled 5, 4, 2, making 11
```
=> Implement "!8ball" and "roll"

ircbot/plugin/bless.py
Is this more or less sacrilegious if I'm religious?
=> Create has been granted priesthood in the church of emacs

README.md, ircbot/plugin/bless.py
- TIL pre-commit
- Fixed my typos
- Added useful info to the README
- I suck at computers
=> Fixing my previous PR

ircbot/plugin/check.py
=> check: add more colors for new groups

ircbot/plugin/spongebob.py
Exponentially increase the chance of a case switch on duplicates.
No more bad spongebobs!
[Here](https://i.fluffy.cc/2fwMWNJjbsjhRmFt4fq6qJpZCzV0PWcZ.html) are some spongebobs I ran in sequence.
=> plugin: give spongebob a better caps distribution

ircbot/plugin/wide.py
constants capitalized for style, some logic slightly simplified, use partials everywhere for consistency
=> widetext: some improvements

ircbot/plugin/gambling.py
We need to be able to make important life decisions (marriages, which final to study for, whether or not to accept a pull request) through create. This pull request adds the necessary functionality.
=> Add !choice

Makefile, ircbot/ircbot.py, ircbot/plugin/help.py
someone was running jupyter on 8888 on supernova, making the help page error out. let's just fix this for everyone.
=> help: make ircbot development more supernova friendly.

ircbot/plugin/twitter.py
test tweet: https://twitter.com/realDonaldTrump/status/1078412737603096576
old create:
@\realDonaldTrump (Donald J. Trump): THIs iSn’T AboUt THe wALl,eVerYBOdy KnOWs THaT a wALL wiLL work PerFEctlY (In iSraEl THe Wall WOrkS 99.9%). tHiS iS OnLy abOUt thE dems NOt leTTiNG doNAld TruMp **&Amp;** The REpuBLiCAnS haVe A wIN. thEY mAY haVe tHE 10 seNatE VOtES,bUT wE HavE thE iSsue, bORdEr seCuRItY. 2020!
new create:
@\realDonaldTrump (Donald J. Trump): tHis ISn’T aBoUT thE wAll, EvERybOdY KnowS ThaT a wAlL wILl wORk PErfEcTLy (in IsRAel THe WAlL WoRKs 99.9%). thIs is ONlY aBOuT The DeMS nOt LEttIng DoNalD tRUMP **&** thE rePubLicANs HaVe a wiN. TheY maY HAvE The 10 SeNAtE vOtES, BuT wE HavE tHe ISsUe, BORDer SecUriTY. 2020!
=> parse html-encoded tweets instead of dumping &amp; in IRC

ircbot/ircbot.py
so create doesn't crash anytime anyone says "create status"
=> add fallback error handling for all plugins

ircbot/plugin/turing.py, requirements-minimal.txt, requirements.txt
creates a markov chain model from the quotes and inspire databases.
create uses this model to return... interesting mixtures of the two.
Here are some of my [favorites](https://i.fluffy.cc/S90VX4B4PftGS4BlpTwcWSj9zdV2fcxc.html). You can play with it in #test. `#create-keur: turing` will trigger it.
=> plugin: add turing

ircbot/plugin/scramble.py
A plugin that scrambles words in a sentence.
=> plugin: add scramble

ircbot/plugin/weather.py
=> add friendly support for our celsius readers

ircbot/plugin/scramble.py
- Keep the positions of the first and the last letter of each word.
- Formalize docstrings.
Signed-off-by: Yuan Zhou <jerryzhou@ocf.berkeley.edu>
=> plugin: update scramble

ircbot/plugin/pipe.py
Pipe the output of a command to the input of the next command.
Signed-off-by: Yuan Zhou <jerryzhou@ocf.berkeley.edu>
=> plugin: add pipe

.gitignore, Makefile, README.md, ircbot/plugin/emoji.py, ircbot/plugin/wide.py, requirements-dev.txt
This is the minimal change set needed to have mypy start checking ircbot. Hopefully we can start annotating more functions and improve type checking coverage.
=> Add mypy checking to ircbot

.gitignore, Makefile, README.md, ircbot/plugin/emoji.py, ircbot/plugin/wide.py, requirements-dev.txt
=> Revert "Add mypy checking to ircbot"

.pre-commit-config.yaml, Dockerfile, Makefile
=> Revert "create => python3.7"

ircbot/plugin/kanboard.py
=> Kanboard integration

ircbot/ircbot.py
You can now yell at CREATE. No more having to retype your message after your phone autocapitalizes the first letter.
fixes #115
=> Mentioning "create" is now case insensitive

ircbot/plugin/reverse.py
Because I feel spammy so feel free to kill this pr :3
=> add reverse fun-ctionality

.pre-commit-config.yaml, Dockerfile, Makefile, ircbot/ircbot.py, ircbot/plugin/channels.py, ircbot/plugin/check.py, ircbot/plugin/create.py, ircbot/plugin/dns.py, ircbot/plugin/emoji.py, ircbot/plugin/google.py, ircbot/plugin/inspire.py, ircbot/plugin/lab.py, ircbot/plugin/macros.py, ircbot/plugin/magic.py, ircbot/plugin/marathon.py, ircbot/plugin/quotes.py, ircbot/plugin/regex.py, ircbot/plugin/shorturls.py, ircbot/plugin/twitter.py, ircbot/plugin/weather.py, ircbot/plugin/what_is.py
Also add pyupgrade for fstring goodness. I had to change the google plugin manually due to https://github.com/asottile/pyupgrade/issues/134
=> Update to Python3.7

.gitignore, Makefile, ircbot/ircbot.py, ircbot/plugin/debian_security.py, ircbot/plugin/dns.py, ircbot/plugin/emoji.py, ircbot/plugin/help.py, ircbot/plugin/pipe.py, ircbot/plugin/stack_exchange.py, ircbot/plugin/wide.py, mypy.ini, requirements-dev.txt
Because create can never be over engineered.
=> Initial clean mypy run

ircbot/plugin/dns.py
Someone pls verify i did this right
=> dns: allow question mark in "what is it not"

ircbot/plugin/lab.py
\<fydai> petition to create a shorter command for that so it's easier for me to type while driving
=> Add "wiitl" as a trigger for labstaff check

ircbot/plugin/still.py
Based on my twitch irc bot's command: https://github.com/anthonywritescode/twitch-chat-bot/blob/e8f3093fb4acb31bd89942c16110f5a8e78f6ea4/bot.py#L160-L166
=> Add !still command

ircbot/plugin/sux.py
=> add "has a small truck" to !sux

ircbot/plugin/google.py
This adds a layer of abstraction for making general Google searches, and adds a youtube function that does the same thing as regular Google but adds site:youtube.com to the query.
=> google: add !yt command for youtube search

ircbot/plugin/weather.py
the weather isn't 2500 degrees (stop multiplying the temperature by 32 for the sake of calculating the icon)
=> Fixed the F2C Conversion

ircbot/ircbot.py
You can now DM create, e.g.:
```
[08:46:13]  <ckuehl> help
[08:46:13]  <create-ckuehl> https://ircbot.ocf.berkeley.edu/
[08:46:15]  <ckuehl> !flip
[08:46:15]  <create-ckuehl> my quantum randomness says: reject
[08:46:20]  <ckuehl> list
[08:46:20]  <create-ckuehl> no pending requests
[08:46:23]  <ckuehl> roll 1d3
[08:46:24]  <create-ckuehl> i rolled 1, making 1
[08:47:05]  <ckuehl> hello world
[08:47:07]  <ckuehl> s/hello/yellow/
[08:47:07]  <create-ckuehl> <ckuehl> yellow world
```
It's basically like the normal channel interface, except:
* No operator/privileged commands
* You don't have to ping create since that makes no sense in a DM
* create won't ping you in responses for the same reason
I think I tested adequately to make sure I didn't break the channel interface while doing this.
=> Add support for direct messaging create

ircbot/plugin/timer.py
This reverts commit 712f6350d220be36ebc8d8cf384624123ee5f4dd.
=> Revert "disable DSA checking while they're throwing 403s"

Dockerfile, services/ircbot/log/run, services/ircbot/run
=> Logs go directly to stdout

ircbot/plugin/sux.py
Now with 200% less racism against Asian Americans
- Added 'abolish {0}',
- Added 'society has progressed beyond the need for {0}'
=> Adding extra ways to sux

ircbot/plugin/stack_exchange.py
```
<ckuehl> https://stackoverflow.com/questions/21984553/postgresql-reload-ssl-conf-files-without-restart
<create> Stack Overflow: postgresql reload ssl conf files without restart | 1 votes, 1 answers | February 24, 2014
<create-ckuehl> Stack Overflow: postgresql reload ssl conf files without restart | 1 vote, 1 answer | February 24, 2014
```
```
<ckuehl> https://stackoverflow.com/questions/3811678/add-two-variables-using-jquery
<create-ckuehl> Stack Overflow: Add two variables using jquery | 27 votes, 6 answers | September 28, 2010
<create> Stack Overflow: Add two variables using jquery | 27 votes, 6 answers | September 28, 2010
```
=> Fix pluralization in Stack Exchange links

ircbot/plugin/fire.py
I wrote this in the github web editor so we pray
=> add is california on fire plugin

ircbot/plugin/weather.py
The openweathermap API only returns a score from 1-5 so I calculate the AQI using the EPA formula.
=> Add AQI output to weather

ircbot/plugin/group.py, requirements.txt
Decided to change the trigger from "!group" and "!subdomain" to "create: group" and "create: subdomain" for consistency. Also added the ability for it to distinguish mail vhost and web vhost.
=> changed trigger command and added mail and web hosting info

ircbot/plugin/group.py
Realized that it makes sense to be able to list/search through our apphosts as well
=> added apphost feature to group.py
